"""align schema with models

Revision ID: 615c60ad3e29
Revises: 
Create Date: 2026-07-16 15:57:22.019093

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '615c60ad3e29'
down_revision: Union[str, Sequence[str], None] = 'c0ffee000001'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def _index_names(table: str) -> set[str]:
    bind = op.get_bind()
    inspector = sa.inspect(bind)
    if table not in inspector.get_table_names():
        return set()
    return {ix["name"] for ix in inspector.get_indexes(table) if ix.get("name")}


def upgrade() -> None:
    """Upgrade schema. Skips when already at modern layout (fresh create_initial)."""
    activity_indexes = _index_names("activity")
    if "ix_activity_actor_user_id" in activity_indexes and "ix_activity_id" not in activity_indexes:
        return

    op.alter_column('activity', 'actor_user_id',
               existing_type=sa.VARCHAR(),
               nullable=False)
    if "ix_activity_id" in activity_indexes:
        op.drop_index(op.f('ix_activity_id'), table_name='activity')
    if "ix_activity_actor_user_id" not in activity_indexes:
        op.create_index(op.f('ix_activity_actor_user_id'), 'activity', ['actor_user_id'], unique=False)
    if "ix_activity_user_invite_id" not in activity_indexes:
        op.create_index(op.f('ix_activity_user_invite_id'), 'activity', ['user_invite_id'], unique=False)

    job_indexes = _index_names("jobbs")
    op.alter_column('jobbs', 'id',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=False,
               existing_server_default=sa.text("nextval('jobbs_id_seq'::regclass)"))
    op.alter_column('jobbs', 'user_id',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               nullable=False)
    if "ix_jobbs_id" in job_indexes:
        op.drop_index(op.f('ix_jobbs_id'), table_name='jobbs')
    if "ix_jobbs_user_id" not in job_indexes:
        op.create_index(op.f('ix_jobbs_user_id'), 'jobbs', ['user_id'], unique=False)
    op.create_foreign_key(None, 'jobbs', 'users', ['user_id'], ['id'])

    invite_indexes = _index_names("user_invites")
    if "ix_user_invites_email" in invite_indexes:
        op.drop_index(op.f('ix_user_invites_email'), table_name='user_invites')
    if "ix_user_invites_id" in invite_indexes:
        op.drop_index(op.f('ix_user_invites_id'), table_name='user_invites')
    if "ix_user_invites_token" in invite_indexes:
        op.drop_index(op.f('ix_user_invites_token'), table_name='user_invites')
    if "ix_user_invites_invited_by_id" not in invite_indexes:
        op.create_index(op.f('ix_user_invites_invited_by_id'), 'user_invites', ['invited_by_id'], unique=False)
    op.create_unique_constraint(None, 'user_invites', ['token'])
    op.create_unique_constraint(None, 'user_invites', ['email'])

    user_indexes = _index_names("users")
    if "ix_users_email" in user_indexes:
        op.drop_index(op.f('ix_users_email'), table_name='users')
    if "ix_users_id" in user_indexes:
        op.drop_index(op.f('ix_users_id'), table_name='users')
    if "ix_users_user_invite_id" in user_indexes:
        op.drop_index(op.f('ix_users_user_invite_id'), table_name='users')
    op.create_unique_constraint(None, 'users', ['email'])
    op.create_unique_constraint(None, 'users', ['user_invite_id'])


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='unique')
    op.drop_constraint(None, 'users', type_='unique')
    op.create_index(op.f('ix_users_user_invite_id'), 'users', ['user_invite_id'], unique=True)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.drop_constraint(None, 'user_invites', type_='unique')
    op.drop_constraint(None, 'user_invites', type_='unique')
    op.drop_index(op.f('ix_user_invites_invited_by_id'), table_name='user_invites')
    op.create_index(op.f('ix_user_invites_token'), 'user_invites', ['token'], unique=True)
    op.create_index(op.f('ix_user_invites_id'), 'user_invites', ['id'], unique=False)
    op.create_index(op.f('ix_user_invites_email'), 'user_invites', ['email'], unique=False)
    op.drop_constraint(None, 'jobbs', type_='foreignkey')
    op.drop_index(op.f('ix_jobbs_user_id'), table_name='jobbs')
    op.create_index(op.f('ix_jobbs_id'), 'jobbs', ['id'], unique=False)
    op.alter_column('jobbs', 'user_id',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               nullable=True)
    op.alter_column('jobbs', 'id',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=False,
               existing_server_default=sa.text("nextval('jobbs_id_seq'::regclass)"))
    op.drop_index(op.f('ix_activity_user_invite_id'), table_name='activity')
    op.drop_index(op.f('ix_activity_actor_user_id'), table_name='activity')
    op.create_index(op.f('ix_activity_id'), 'activity', ['id'], unique=False)
    op.alter_column('activity', 'actor_user_id',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###
